save_best: True
plot_agents: True
verbose: True

logger:
            classname: bbrl.utils.logger.TFLogger
            log_dir: ./cem_logs/
            verbose: False
            every_n_seconds: 10

algorithm:
      seed:
            train: 335
            eval: 983
            actor: 123
            torch: 7
      sigma: 0.1
      n_envs_train: 1
      n_envs_eval: 10
      n_steps: 70000
      noise_multiplier: 0.99
      pop_size: 10
      elites_nb: 5
      actor_type: ContinuousDeterministicActor
      architecture:
            actor_hidden_size: [4, 4]

gym_env:
      env_name: MountainCarContinuous-v0
