save_best: False
plot_agents: True
collect_stats: False

log_dir: ./tmp
video_dir: ${log_dir}/videos

hydra:
  run:
    dir: ${log_dir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

logger:
      classname: bbrl.utils.logger.WandbLogger
      project: "droQ_continuous"
      group: "droQ_lunar_lander_beta"
      tags: "droQ"
      job_type: test
      log_dir: ${log_dir}
      cache_size: 10000
      every_n_seconds: 10
      verbose: False

algorithm:

      seed:
        train: 2
        eval: 9
        q: 1
        act: 2
        explorer: 4
        torch: 7

      nb_seeds: 4
      max_grad_norm: 0.5
      buffer_size: 2e5
      n_envs: 8
      n_steps_train: 32
      n_steps: 1_200_000
      optim_n_updates: 1
      batch_size: 64
      tau_target: 0.05
      eval_interval: 3000
      learning_starts: 10000
      nb_evals: 10
      action_noise: 0.1
      discount_factor: 0.999
      architecture:
        actor_hidden_size: [64]
        critic_hidden_size: [64, 64, 64, 64]

      alpha: 0.01

gym_env:
      classname: __main__.make_gym_env
      env_name: Ant-v4

actor_optimizer:
      classname: torch.optim.Adam
      lr: 5e-4

critic_optimizer:
      classname: torch.optim.Adam
      lr: 2e-3
